app:
    resource: '@AppBundle/Controller/'
    type: annotation
article_show:
    path:	/articles/{lang}/{year}/{title}.{_format}
    defaults:	{	_controller:	AcmeBundle:Article:show,	_format:	html	}
    methods:		[GET]
    requirements:
        lang:	en|fr|ru
        _format:	html|rss
        _locale:	ru
        year:	\d+
