<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYpkax1b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYpkax1b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYpkax1b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYpkax1b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYpkax1b\appDevDebugProjectContainer();
